config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :line_items
    resources :orders
    resources :carts
    resources :products
    resources :categories

    resources :users, only: [:index, :show, :edit, :update, :destroy] # after devise_for :users!!!!
  end

  resources :carts, only: [:show, :update]
  # resources :categories, only: [:index, :show]
  resources :line_items, only: [:update, :destroy]
  resources :orders, only: [:show, :new, :create]  
  resources :products, only: [:index, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] # after devise_for :users!!!!

  root to: "products#index"

  get '/description' => 'pages#description'
  get '/reference' => 'pages#reference'
  
  get '/reset' => 'reset#reset'
  delete '/regenerate' => 'reset#regenerate'

end

app/models/order.rb
class Order < ApplicationRecord

  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]

  validates :pay_type, inclusion: PAYMENT_TYPES  

  belongs_to :user, :inverse_of => :order

  has_many :line_items, dependent: :destroy, :inverse_of => :order

  def fill_in
  	
  	user.cart.line_items.each do |line_item|

  		line_item.cart_id = nil

  		line_items << line_item

  	end
  end

  def total
    line_items.inject(0) {|sum, x| sum += x.product.price * x.quantity }
  end
    
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /admin/orders
  # GET /admin/orders.json
  def index
    @orders = Order.all
  end

  # GET /admin/orders/1
  # GET /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders
  # POST /admin/orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1
  # PATCH/PUT /admin/orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1
  # DELETE /admin/orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :pay_type)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!

  before_action :set_order, only: [:show, :edit, :update, :destroy]

  before_action :check_order, only: [:create]

  before_action :xhr_history, only: [:new, :create]

  # # GET /orders
  # # GET /orders.json
  # def index
  #   @orders = Order.where(user_id: current_user.id).order(:created_at)
  # end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # # GET /orders/1/edit
  # def edit
  # end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    @order.fill_in

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }        
      end
    end
  end

  # # PATCH/PUT /orders/1
  # # PATCH/PUT /orders/1.json
  # def update
  #   respond_to do |format|
  #     if @order.update(order_params)

  #       @order.fill_in

  #       format.html { redirect_to @order, notice: 'Order was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @order }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /orders/1
  # # DELETE /orders/1.json
  # def destroy
  #   @order.destroy
  #   respond_to do |format|
  #     format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      par = params.require(:order).permit(:user_id, :pay_type)
      if action_name == "create"
        par[:user_id] = current_user.id
      end
      par
    end

    def check_order

      if !current_user.cart || current_user.cart.line_items.empty?

        respond_to do |format|

          format.html { redirect_back(fallback_location: products_path, notice: 'Your cart is empty.') }

        end

      end

      if current_user.name.blank?

        respond_to do |format|

          format.html { redirect_back(fallback_location: products_path, notice: 'You did not provide your name in your user profile.') }

        end

      end

      if current_user.address.blank?

        respond_to do |format|

          format.html { redirect_back(fallback_location: products_path, notice: 'You did not provide your address in your user profile.') }

        end

      end

    end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for([:admin, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
    </div>
  <div class="field">
      <%= f.label :pay_type %><br>
    <%= f.text_field :pay_type %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @order] %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<h2>Orders</h2>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Pay type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', [:admin, order] %></td>
        <td><%= link_to 'Edit', edit_admin_order_path(order) %></td>
        <td><%= link_to 'Destroy', [:admin, order], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Order', new_admin_order_path %>

app/views/admin/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<p>
  <strong>User:</strong>
  <%= @order.user.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>