config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :line_items
    resources :orders
    resources :carts
    resources :products
    resources :categories

    resources :users, only: [:index, :show, :edit, :update, :destroy] # after devise_for :users!!!!
  end

  resources :carts, only: [:show, :update]
  # resources :categories, only: [:index, :show]
  resources :line_items, only: [:update, :destroy]
  resources :orders, only: [:show, :new, :create]  
  resources :products, only: [:index, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] # after devise_for :users!!!!

  root to: "products#index"

  get '/description' => 'pages#description'
  get '/reference' => 'pages#reference'
  
  get '/reset' => 'reset#reset'
  delete '/regenerate' => 'reset#regenerate'

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, :inverse_of => :cart, optional: true

  has_many :line_items, dependent: :destroy, :inverse_of => :cart

  def add_product add_product_id, add_product_quantity

  	line_item = self.line_items.find_by product_id: add_product_id

  	if line_item

  		line_item.quantity += add_product_quantity.to_i
  		line_item.save!

  	else

  		self.line_items.create product_id: add_product_id, quantity: add_product_quantity
  		
  	end
  end

  def move_cart_content other_cart

    if other_cart && other_cart.try(:line_items) && !other_cart.line_items.empty?

      other_cart.line_items.each do |other_line_item|

        add_product other_line_item.product.id, other_line_item.quantity

      end

      other_cart.line_items.clear

    end

  end

  def total
    line_items.inject(0) {|sum, x| sum += x.product.price * x.quantity }
  end

end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < Admin::ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /admin/carts
  # GET /admin/carts.json
  def index
    @carts = Cart.all
  end

  # GET /admin/carts/1
  # GET /admin/carts/1.json
  def show
  end

  # GET /admin/carts/new
  def new
    @cart = Cart.new
  end

  # GET /admin/carts/1/edit
  def edit
  end

  # POST /admin/carts
  # POST /admin/carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to [:admin, @cart], notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/carts/1
  # PATCH/PUT /admin/carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to [:admin, @cart], notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/carts/1
  # DELETE /admin/carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to admin_carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  before_action :check_clear_cart, only: [:update]

  before_action :check_cart_add_product, only: [:update]

  before_action :xhr_history, only: [:update, :show]

  # GET /carts
  # GET /carts.json
  # def index
  #   @carts = Cart.all
  # end

  # GET /carts/1
  # GET /carts/1.json
  def show
    respond_to do |format|
      format.html {}
      # format.json {}
      # flash.now[:notice] = "The product was added to the cart." 
      format.js {}
    end
  end

  # # GET /carts/new
  # def new
  #   @cart = Cart.new
  # end

  # # GET /carts/1/edit
  # def edit
  # end

  # # POST /carts
  # # POST /carts.json
  # def create
  #   @cart = Cart.new(cart_params)

  #   respond_to do |format|
  #     if @cart.save
  #       format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
  #       format.json { render :show, status: :created, location: @cart }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @cart.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
        flash.now[:notice] = @flash_notice
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
        flash.now[:notice] = "Error (this did not happen): " + @flash_notice
        format.js {}
      end
    end
  end

  # # DELETE /carts/1
  # # DELETE /carts/1.json
  # def destroy
  #   @cart.destroy
  #   respond_to do |format|
  #     format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :id, :clear_line_items)
    end

    def check_cart_add_product

      if params[:add_product_id]

        @cart.add_product params[:add_product_id], params[:add_product_quantity]

        @flash_notice = "The product was added to the cart."

      end

    end

    def check_clear_cart

      if params[:clear_line_items]

        @cart.line_items.clear

        @flash_notice = "Your cart was successfully emptied."

      end

    end    
end

app/helpers/admin/carts_helper.rb
module Admin::CartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :cart_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_p_show.html.erb
<h2>Your cart</h2>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.line_items.each do |line_item| %>
      <tr>
        <td><img src="<%= single_attachment_url_280(line_item.product) %>" style="width:140px;"></td>
        <td><%= line_item.product.try(:title) %></td>
        <td><%= number_to_currency line_item.product.try(:price) %></td>
        <td>
          <%= form_for line_item, remote: true, method: :patch do |f| %>  
          <%= f.number_field :quantity %>    
          <%= f.submit 'Update' %>
          <% end %>
        </td>        
        <td><%= button_to 'X', line_item, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<% unless @cart.line_items.empty? %>

  <div class="field">
    Total:
    <%= number_to_currency @cart.total %>
  </div>

  <br>

  <%= button_to "Checkout", new_order_path, remote: false, method: :get, form_class: "inline-block" %>&nbsp;
  <%# http://stackoverflow.com/questions/4886963/how-to-add-additional-params-to-a-button-to-form  %>
  <%= button_to 'Empty cart', cart_path, remote: true, method: :patch,
      data: { confirm: 'Are you sure?' }, form_class: "inline-block",
      params: { "cart[id]" => @cart.id, "clear_line_items" => true } %>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render :partial => "p_show" %>

app/views/carts/show.js.erb
$('#errors').html("<%= escape_javascript render partial: "layouts/errors", locals: {obj: @cart} %>");

$('#main').html("<%= escape_javascript render :partial => "p_show" %>");

$('#products_menu').html("<%= escape_javascript render :partial => "layouts/products_menu" %>");

app/views/carts/update.js.erb
$('#errors').html("<%= escape_javascript render partial: "layouts/errors", locals: {obj: @cart} %>");

$('#cart').html("<%= escape_javascript render :partial => "layouts/cart" %>");

<% if params[:clear_line_items] %>

	$('#main').html("<%= escape_javascript render :partial => "p_show" %>");

<% end %>